### ISSUE TITLE
can't get through configuration, if I choose not to encrypt files

### ISSUE THREAD

**Issue by ejheil** [TobiasTheViking/flickrannex#2]
```
[21:57:58 PM]$ python flickrannex.py
Please enter your flickr email address: (my email)
Please enter your flickr password: (my password)
Should uploaded files be encryptes [yes/no]: no
Traceback (most recent call last):
  File "flickrannex.py", line 305, in <module>
    main()
  File "flickrannex.py", line 269, in main
    if not conf["encrypted"] and not verifyFileType(ANNEX_KEY):
  File "flickrannex.py", line 50, in verifyFileType
    fname, ext = os.path.splitext(os.path.basename(filename))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 112, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
~/flickrannex (master u=)
[21:58:23 PM]$ 
```

I've already set up the api key just fine, and worked through an issue where it was failing because my contact email was different than my yahoo login.

**Comment by TobiasTheViking** [comment]
Fixed in version 0.1.1

Thanks for your report.
