### ISSUE TITLE
failed "git annex get" from flickr: "PNG file has invalid signature"

### ISSUE THREAD

**Issue by ejheil** [TobiasTheViking/flickrannex#4]
I updated my git annex by building from trunk yesterday.  I can now upload to flickr!  But not download.  This is using flickrannex v0.1.2.

[10:00:18 AM]$ git annex version
git-annex version: 4.20130527-gad9ba6f

Demonstration of the problem:

```
[09:53:25 AM]$ mkdir myflickrannex
~
[09:53:36 AM]$ cd myflickrannex/
~/myflickrannex
[09:53:40 AM]$ git init
Initialized empty Git repository in /Users/ed/myflickrannex/.git/
~/myflickrannex (master #)
[09:53:45 AM]$ git annex init
init  ok
(Recording state in git...)
~/myflickrannex (master #)
[09:53:47 AM]$ cat .git/config 
[core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
    ignorecase = true
    precomposeunicode = false
[annex]
    uuid = 74d0a040-df3c-4df3-82e9-b76c2391df8e
    version = 3
~/myflickrannex (master #)
[09:54:29 AM]$ git config annex.flickr-hook '/usr/bin/python /Users/ed/code/flickrannex/flickrannex.py'
~/myflickrannex (master #)
[09:56:40 AM]$ git annex initremote flickr type=hook hooktype=flickr encryption=none
initremote flickr ok
(Recording state in git...)
~/myflickrannex (master #)
[09:58:02 AM]$ git annex describe flickr "the flickr library"
describe flickr ok
(Recording state in git...)
~/myflickrannex (master #)
[09:58:13 AM]$ cp ~/Pictures/0111021718.jpg ./~/myflickrannex (master #%)
[09:58:57 AM]$ git annex add 0111021718.jpg
add 0111021718.jpg (checksum...) ok
(Recording state in git...)
~/myflickrannex (master #)
[09:59:07 AM]$ git annex copy --to=flickr 0111021718.jpg
copy 0111021718.jpg (checking flickr...) (to flickr...) 
/Users/ed/code/flickrannex/flickrannex.py:92: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  if res:
/Users/ed/code/flickrannex/flickrannex.py:100: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  if res:
ok
(Recording state in git...)
~/myflickrannex (master #)
[10:00:04 AM]$ git annex drop 0111021718.jpg
drop 0111021718.jpg (checking flickr...) ok
(Recording state in git...)
~/myflickrannex (master #)
[10:00:11 AM]$ git annex get 0111021718.jpg
get 0111021718.jpg (from flickr...) 
Traceback (most recent call last):
  File "/Users/ed/code/flickrannex/flickrannex.py", line 306, in <module>
    main()
  File "/Users/ed/code/flickrannex/flickrannex.py", line 279, in main
    getFile(ANNEX_KEY, ANNEX_FILE, ANNEX_FOLDER)
  File "/Users/ed/code/flickrannex/flickrannex.py", line 152, in getFile
    width, height, pixels, meta, text = r.read()
  File "/Users/ed/code/flickrannex/lib/pypng/png.py", line 1940, in read
    self.preamble(lenient=lenient)
  File "/Users/ed/code/flickrannex/lib/pypng/png.py", line 1734, in preamble
    self.validate_signature()
  File "/Users/ed/code/flickrannex/lib/pypng/png.py", line 1721, in validate_signature
    raise FormatError("PNG file has invalid signature.")
png.FormatError: FormatError: PNG file has invalid signature.

  flickr hook exited nonzero!

  Unable to access these remotes: flickr

  Try making some of these repositories available:
    1ef9a215-a376-4258-8c05-1587b3f376bd -- flickr (the flickr library)
failed
git-annex: get: 1 failed
~/myflickrannex (master #)
[10:00:18 AM]$ 
```

I'm not sure why it's dealing with a PNG when I'm trying to download a jpg?

**Comment by TobiasTheViking** [comment]
That was a stupid bug by my. Sorry.
