### ISSUE TITLE
Failure to log in

### ISSUE THREAD

**Issue by magthe** [TobiasTheViking/flickrannex#6]
It seems `flickrannex` can't find my Flickr user:

```
% ./flickrannex.py
Please make sure your email address has been associated flickr.
Please enter your flickr email address: m.therning@yahoo.com
Please enter your flickr password: my_secret_pwd
Should uploaded files be encryptes [yes/no]: no
Traceback (most recent call last):
  File "./flickrannex.py", line 350, in <module>
    main()
  File "./flickrannex.py", line 290, in main
    login(conf["uname"], conf["pword"])
  File "./flickrannex.py", line 43, in login
    user_id = flickr.people_findByEmail(find_email=uname)
  File "./lib/flickrapi/__init__.py", line 337, in handler
    parse_format=args['format'], **args)
  File "./lib/flickrapi/__init__.py", line 423, in __wrap_in_parser
    return parser(self, data)
  File "./lib/flickrapi/__init__.py", line 264, in parse_etree
    err.attrib['code'], err.attrib['msg']))
flickrapi.exceptions.FlickrError: Error: 1: User not found
```

This is ought to be the email address I've associated with Flickr as the settings page contains the following:

```
You are signed in to Flickr via Google (m.therning@yahoo.com)
```

**Comment by TobiasTheViking** [comment]
Could you please check https://github.com/TobiasTheViking/flickrannex/issues/1 and verify that this is not just an issue with the email address you are using?

**Comment by magthe** [comment]
Indeed, it was #1.  How confusing that thing is.  Thanks for the pointers, now it works nicely.
